project_id = "tpzzjvnsueqpibaraivy"

[functions.analyze-trades]
verify_jwt = false

[functions.check-price-alerts]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-demo-account]
verify_jwt = false

[functions.create-donation]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.generate-chart-pattern]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.manage-linked-account]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.publish-scheduled]
verify_jwt = false

[functions.quinn-chat]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.webauthn-login-options]
verify_jwt = false

[functions.webauthn-login-verify]
verify_jwt = false

[functions.webauthn-register-options]
verify_jwt = false

[functions.webauthn-register-verify]
verify_jwt = false

[functions.symbol-search]
verify_jwt = false