/**
 * PlanGenerator — Ministry Series Planner
 * Full edit, copy, and PDF export after generation.
 */

import { useMemo, useState } from "react";
import {
  BookOpen,
  Check,
  ChevronDown,
  ChevronUp,
  Copy,
  Download,
  Loader2,
  Pencil,
  Sparkles,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";

type PlanWeek = {
  week: number;
  title: string;
  theme: string;
  scripture: string;
  key_idea: string;
  service_elements: string[];
};

type GeneratedPlan = {
  plan_title: string;
  summary: string;
  weeks: PlanWeek[];
  notes?: string;
};

function exportPlanAsPdf(plan: GeneratedPlan) {
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><title>${plan.plan_title}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:Georgia,serif;color:#1a1a1a;padding:48px;max-width:680px;margin:0 auto}
h1{font-size:28px;font-weight:normal;margin-bottom:8px}
.summary{font-size:14px;color:#555;line-height:1.7;margin-bottom:32px;border-bottom:1px solid #ddd;padding-bottom:24px}
.week{margin-bottom:28px;page-break-inside:avoid}
.wk{font-size:11px;text-transform:uppercase;letter-spacing:.2em;color:#888;margin-bottom:4px}
.wtitle{font-size:18px;margin-bottom:12px}
.fl{font-size:10px;text-transform:uppercase;letter-spacing:.15em;color:#888;margin-bottom:2px;margin-top:10px}
.fv{font-size:13px;color:#222;line-height:1.6}
.ki{font-style:italic}
.tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:4px}
.tag{font-size:11px;border:1px solid #ccc;padding:2px 10px;border-radius:20px;color:#444}
.notes{margin-top:32px;padding-top:20px;border-top:1px solid #ddd;font-size:13px;color:#555;line-height:1.7}
.footer{margin-top:48px;font-size:10px;color:#bbb;text-align:center}
</style></head><body>
<h1>${plan.plan_title}</h1>
<p class="summary">${plan.summary}</p>
${plan.weeks
  .map(
    (w) => `
<div class="week">
<div class="wk">Week ${w.week}</div>
<div class="wtitle">${w.title}</div>
<div class="fl">Theme</div><div class="fv">${w.theme}</div>
<div class="fl">Scripture</div><div class="fv">${w.scripture}</div>
<div class="fl">Key Idea</div><div class="fv ki">"${w.key_idea}"</div>
${w.service_elements?.length ? `<div class="fl">Service Elements</div><div class="tags">${w.service_elements.map((el) => `<span class="tag">${el}</span>`).join("")}</div>` : ""}
</div>`,
  )
  .join("")}
${plan.notes ? `<div class="notes"><strong>Pastoral Notes</strong><br/>${plan.notes}</div>` : ""}
<div class="footer">Generated by SanctumIQ · Into Innovations LLC</div>
</body></html>`;

  const win = window.open("", "_blank", "noopener,noreferrer");
  if (!win) {
    toast.error("Pop-up blocked — allow pop-ups and try again.");
    return;
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}

function planAsText(plan: GeneratedPlan): string {
  const lines: string[] = [plan.plan_title, "─".repeat(40), "", plan.summary, ""];
  plan.weeks.forEach((w) => {
    lines.push(`WEEK ${w.week} — ${w.title}`);
    lines.push(`Theme: ${w.theme}`);
    lines.push(`Scripture: ${w.scripture}`);
    lines.push(`Key Idea: "${w.key_idea}"`);
    if (w.service_elements?.length)
      lines.push(`Service Elements: ${w.service_elements.join(", ")}`);
    lines.push("");
  });
  if (plan.notes) {
    lines.push("Pastoral Notes:");
    lines.push(plan.notes);
  }
  return lines.join("\n");
}

function WeekCard({
  week,
  isOpen,
  onToggle,
  onChange,
}: {
  week: PlanWeek;
  isOpen: boolean;
  onToggle: () => void;
  onChange: (patch: Partial<PlanWeek>) => void;
}) {
  return (
    <div className="rounded-2xl border border-gold/15 bg-white/[0.02] overflow-hidden">
      <button
        type="button"
        onClick={onToggle}
        className="w-full flex items-center justify-between px-5 py-3.5 hover:bg-gold/5 transition-colors"
      >
        <div className="flex items-center gap-3 text-left min-w-0">
          <span className="text-[10px] uppercase tracking-[0.22em] text-gold/55 shrink-0">
            Week {week.week}
          </span>
          <span className="font-display text-base text-foreground/90 truncate">{week.title}</span>
        </div>
        {isOpen ? (
          <ChevronUp className="h-4 w-4 text-muted-foreground/40 shrink-0" />
        ) : (
          <ChevronDown className="h-4 w-4 text-muted-foreground/40 shrink-0" />
        )}
      </button>

      {isOpen && (
        <div className="px-5 pb-5 space-y-4 border-t border-gold/10">
          <div className="pt-4">
            <p className="text-[10px] uppercase tracking-[0.2em] text-gold/50 mb-1">Title</p>
            <input
              value={week.title}
              onChange={(e) => onChange({ title: e.target.value })}
              className="w-full bg-transparent text-base font-display text-foreground outline-none border-b border-gold/15 pb-1 focus:border-gold/40 transition-colors"
              aria-label="Input"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <p className="text-[10px] uppercase tracking-[0.2em] text-gold/50 mb-1">Theme</p>
              <input
                value={week.theme}
                onChange={(e) => onChange({ theme: e.target.value })}
                className="w-full bg-transparent text-sm text-foreground/85 outline-none border-b border-gold/12 pb-1 focus:border-gold/35 transition-colors"
                aria-label="Input"
              />
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-[0.2em] text-gold/50 mb-1">Scripture</p>
              <div className="flex items-center gap-1.5">
                <BookOpen className="h-3 w-3 text-gold/40 shrink-0" strokeWidth={1.5} />
                <input
                  value={week.scripture}
                  onChange={(e) => onChange({ scripture: e.target.value })}
                  className="flex-1 bg-transparent text-sm text-gold-soft/80 outline-none border-b border-gold/12 pb-1 focus:border-gold/35 transition-colors"
                  aria-label="Input"
                />
              </div>
            </div>
          </div>

          <div>
            <p className="text-[10px] uppercase tracking-[0.2em] text-gold/50 mb-1.5">Key idea</p>
            <textarea
              value={week.key_idea}
              onChange={(e) => onChange({ key_idea: e.target.value })}
              rows={2}
              className="w-full resize-none bg-transparent text-sm text-foreground/80 italic font-display leading-relaxed outline-none border-b border-gold/12 pb-1 focus:border-gold/35 transition-colors"
            />
          </div>

          {week.service_elements?.length > 0 && (
            <div>
              <p className="text-[10px] uppercase tracking-[0.2em] text-gold/50 mb-2">
                Service elements{" "}
                <span className="ml-1 text-muted-foreground/35 normal-case tracking-normal">
                  (tap × to remove)
                </span>
              </p>
              <div className="flex flex-wrap gap-2">
                {week.service_elements.map((el, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center gap-1 rounded-full border border-gold/18 bg-gold/8 pl-3 pr-2 py-1 text-[11px] text-gold-soft/80"
                  >
                    {el}
                    <button
                      type="button"
                      onClick={() =>
                        onChange({
                          service_elements: week.service_elements.filter((_, j) => j !== i),
                        })
                      }
                      className="text-muted-foreground/40 hover:text-foreground transition-colors ml-0.5"
                    >
                      <X className="h-2.5 w-2.5" />
                    </button>
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export function PlanGenerator({ userId }: { userId: string }) {
  const [thought, setThought] = useState("");
  const [plan, setPlan] = useState<GeneratedPlan | null>(null);
  const [generating, setGenerating] = useState(false);
  const [expandedWeeks, setExpandedWeeks] = useState<Set<number>>(new Set([1]));
  const [copied, setCopied] = useState(false);
  const timezone = useMemo(() => Intl.DateTimeFormat().resolvedOptions().timeZone, []);

  const handleGenerate = async () => {
    if (thought.trim().length < 4) {
      toast.error("Add a little more detail first.");
      return;
    }
    setGenerating(true);
    setPlan(null);
    setExpandedWeeks(new Set([1]));
    try {
      const today = new Date().toISOString().slice(0, 10);
      const { data, error } = await supabase.functions.invoke<GeneratedPlan>("plan-generator", {
        body: { thought: thought.trim(), timezone, today },
      });
      if (error) throw error;
      if (!data?.weeks?.length) throw new Error("No plan returned. Try again.");
      setPlan(data);
      if (data.weeks.length <= 4) setExpandedWeeks(new Set(data.weeks.map((w) => w.week)));
      toast.success(`${data.plan_title} — ${data.weeks.length} weeks`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Could not generate plan.");
    } finally {
      setGenerating(false);
    }
  };

  const updateWeek = (weekNum: number, patch: Partial<PlanWeek>) => {
    if (!plan) return;
    setPlan({
      ...plan,
      weeks: plan.weeks.map((w) => (w.week === weekNum ? { ...w, ...patch } : w)),
    });
  };

  const toggleWeek = (week: number) => {
    setExpandedWeeks((prev) => {
      const next = new Set(prev);
      if (next.has(week)) next.delete(week);
      else next.add(week);
      return next;
    });
  };

  const handleCopy = async () => {
    if (!plan) return;
    try {
      await navigator.clipboard.writeText(planAsText(plan));
      setCopied(true);
      toast.success("Plan copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Could not copy");
    }
  };

  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-gold/18 bg-white/[0.03] p-5">
        <p className="text-[10px] uppercase tracking-[0.28em] text-gold/70 mb-3">
          Ministry Plan Generator
        </p>
        <textarea
          value={thought}
          onChange={(e) => setThought(e.target.value)}
          rows={3}
          placeholder="A 4-week series on the Beatitudes starting next Sunday, with midweek prayer and a closing community meal…"
          className="w-full resize-none rounded-xl border border-gold/15 bg-obsidian/60 px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground/40 outline-none focus:border-gold/40 transition-colors"
        />
        <div className="mt-3 flex items-center justify-between gap-3">
          <p className="text-[11px] text-muted-foreground/40">{timezone}</p>
          <button
            onClick={handleGenerate}
            disabled={generating || thought.trim().length < 4}
            className={cn(
              "inline-flex items-center gap-2 rounded-xl border border-gold/40 bg-gold/10 px-5 py-2.5 text-sm text-gold-soft transition-colors hover:bg-gold/18 disabled:opacity-40 disabled:cursor-not-allowed",
            )}
          >
            {generating ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="h-4 w-4" strokeWidth={1.5} />
            )}
            {generating ? "Planning…" : "Generate plan"}
          </button>
        </div>
      </div>

      {plan && (
        <div className="space-y-4">
          <div className="rounded-2xl border border-gold/20 bg-white/[0.03] px-5 py-4">
            <div className="flex items-start justify-between gap-3 mb-2">
              <div className="flex-1 min-w-0">
                <p className="text-[10px] uppercase tracking-[0.28em] text-gold/60 mb-1">
                  {plan.weeks.length}-week series
                </p>
                <input
                  value={plan.plan_title}
                  onChange={(e) => setPlan({ ...plan, plan_title: e.target.value })}
                  className="w-full bg-transparent font-display text-xl text-foreground outline-none border-b border-transparent focus:border-gold/30 transition-colors pb-0.5"
                  aria-label="Input"
                />
              </div>
              <div className="flex items-center gap-1 shrink-0">
                <button
                  type="button"
                  onClick={handleCopy}
                  aria-label="Copy plan"
                  className="h-8 w-8 flex items-center justify-center rounded-lg text-muted-foreground/50 hover:text-gold-soft hover:bg-gold/8 transition-colors"
                >
                  {copied ? <Check className="h-4 w-4 text-gold" /> : <Copy className="h-4 w-4" />}
                </button>
                <button
                  type="button"
                  onClick={() => exportPlanAsPdf(plan)}
                  aria-label="Export PDF"
                  className="h-8 w-8 flex items-center justify-center rounded-lg text-muted-foreground/50 hover:text-gold-soft hover:bg-gold/8 transition-colors"
                >
                  <Download className="h-4 w-4" />
                </button>
              </div>
            </div>
            <textarea
              value={plan.summary}
              onChange={(e) => setPlan({ ...plan, summary: e.target.value })}
              rows={2}
              className="w-full resize-none bg-transparent text-sm text-muted-foreground/80 leading-relaxed outline-none"
            />
            <p className="text-[10px] text-muted-foreground/30 mt-2 flex items-center gap-1">
              <Pencil className="h-2.5 w-2.5" /> All fields are editable — tap any text to change it
            </p>
          </div>

          <div className="space-y-2">
            {plan.weeks.map((week) => (
              <WeekCard
                key={week.week}
                week={week}
                isOpen={expandedWeeks.has(week.week)}
                onToggle={() => toggleWeek(week.week)}
                onChange={(patch) => updateWeek(week.week, patch)}
              />
            ))}
          </div>

          {plan.notes && (
            <div className="rounded-2xl border border-gold/12 bg-white/[0.02] px-5 py-4">
              <p className="text-[10px] uppercase tracking-[0.22em] text-gold/50 mb-2">
                Pastoral notes
              </p>
              <textarea
                value={plan.notes}
                onChange={(e) => setPlan({ ...plan, notes: e.target.value })}
                rows={3}
                className="w-full resize-none bg-transparent text-sm text-muted-foreground/75 leading-relaxed outline-none"
              />
            </div>
          )}

          <div className="flex items-center justify-between pt-1">
            <button
              type="button"
              onClick={() => {
                setPlan(null);
                setThought("");
              }}
              className="text-xs text-muted-foreground/40 hover:text-gold-soft transition-colors"
            >
              ↺ Start a new plan
            </button>
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex items-center gap-1.5 text-xs text-muted-foreground/50 hover:text-gold-soft transition-colors"
              >
                {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />} Copy
              </button>
              <button
                type="button"
                onClick={() => exportPlanAsPdf(plan)}
                className="inline-flex items-center gap-1.5 text-xs text-muted-foreground/50 hover:text-gold-soft transition-colors"
              >
                <Download className="h-3.5 w-3.5" /> Export PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
