-- Schedule flag-missed-plans to run daily at 05:00 UTC (end of day for Americas)
-- Requires: vault secrets 'supabase_project_url' and 'supabase_service_role_key'
-- Create via: select vault.create_secret('https://YOUR_PROJECT.supabase.co', 'supabase_project_url');
--             select vault.create_secret('YOUR_SERVICE_ROLE_KEY', 'supabase_service_role_key');
--
-- To enable, uncomment and run (after creating vault secrets):
--
-- select cron.schedule(
--   'flag-missed-plans-daily',
--   '0 5 * * *',
--   $$
--   select net.http_post(
--     url:= (select decrypted_secret from vault.decrypted_secrets where name = 'supabase_project_url') || '/functions/v1/flag-missed-plans',
--     headers:= jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'supabase_service_role_key')
--     ),
--     body:= '{}'::jsonb
--   ) as request_id;
--   $$
-- );
