-- Presence moments: cache for personalized daily nudges generated by Claude
CREATE TABLE IF NOT EXISTS public.presence_moments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_presence_moments_user_generated
  ON public.presence_moments (user_id, generated_at DESC);

ALTER TABLE public.presence_moments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own presence moments"
  ON public.presence_moments FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own presence moments"
  ON public.presence_moments FOR INSERT
  WITH CHECK (auth.uid() = user_id);
