/**
 * feelingVerses.ts — 60 emotions and life situations mapped to 3 KJV verses each.
 * Zero AI. Zero cost. Pure lookup for the Daily Word feature.
 */

export type FeelingVerse = {
  ref: string;
  text: string;
  bookIndex: number;
  chapter: number;
  verse: number;
};

export type FeelingEntry = {
  keywords: string[];
  verses: FeelingVerse[];
};

export const FEELING_MAP: FeelingEntry[] = [
  {
    keywords: [
      "grief over a dream",
      "disappointment",
      "disappointed",
      "let down",
      "crushed",
      "didn't work out",
      "didn't happen",
    ],
    verses: [
      {
        ref: "Psalm 37:4",
        text: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.",
        bookIndex: 18,
        chapter: 37,
        verse: 4,
      },
      {
        ref: "Proverbs 13:12",
        text: "Hope deferred maketh the heart sick: but when the desire cometh, it is a tree of life.",
        bookIndex: 19,
        chapter: 13,
        verse: 12,
      },
      {
        ref: "Romans 5:3",
        text: "We glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope.",
        bookIndex: 44,
        chapter: 5,
        verse: 3,
      },
    ],
  },
  {
    keywords: [
      "longing",
      "missing someone",
      "homesick",
      "far from home",
      "far from family",
      "distance",
    ],
    verses: [
      {
        ref: "Psalm 73:25",
        text: "Whom have I in heaven but thee? and there is none upon earth that I desire beside thee.",
        bookIndex: 18,
        chapter: 73,
        verse: 25,
      },
      {
        ref: "John 14:1",
        text: "Let not your heart be troubled: ye believe in God, believe also in me.",
        bookIndex: 42,
        chapter: 14,
        verse: 1,
      },
      {
        ref: "Isaiah 49:15",
        text: "Can a woman forget her sucking child, that she should not have compassion on the son of her womb? yea, they may forget, yet will I not forget thee.",
        bookIndex: 22,
        chapter: 49,
        verse: 15,
      },
    ],
  },
  {
    keywords: [
      "comparison",
      "comparing",
      "comparing myself",
      "not as good",
      "others have more",
      "why them and not me",
    ],
    verses: [
      {
        ref: "Galatians 6:4",
        text: "But let every man prove his own work, and then shall he have rejoicing in himself alone, and not in another.",
        bookIndex: 47,
        chapter: 6,
        verse: 4,
      },
      {
        ref: "2 Corinthians 10:12",
        text: "They measuring themselves by themselves, and comparing themselves among themselves, are not wise.",
        bookIndex: 46,
        chapter: 10,
        verse: 12,
      },
      {
        ref: "Psalm 139:14",
        text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works.",
        bookIndex: 18,
        chapter: 139,
        verse: 14,
      },
    ],
  },
  {
    keywords: [
      "anxiety",
      "anxious",
      "worry",
      "worried",
      "stress",
      "stressed",
      "nervous",
      "overwhelmed",
      "overthinking",
    ],
    verses: [
      {
        ref: "Philippians 4:6",
        text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
        bookIndex: 49,
        chapter: 4,
        verse: 6,
      },
      {
        ref: "1 Peter 5:7",
        text: "Casting all your care upon him; for he careth for you.",
        bookIndex: 59,
        chapter: 5,
        verse: 7,
      },
      {
        ref: "Matthew 6:34",
        text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.",
        bookIndex: 39,
        chapter: 6,
        verse: 34,
      },
    ],
  },
  {
    keywords: ["fear", "afraid", "scared", "frightened", "terror", "dread", "panic"],
    verses: [
      {
        ref: "Isaiah 41:10",
        text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.",
        bookIndex: 22,
        chapter: 41,
        verse: 10,
      },
      {
        ref: "2 Timothy 1:7",
        text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
        bookIndex: 54,
        chapter: 1,
        verse: 7,
      },
      {
        ref: "Psalm 27:1",
        text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
        bookIndex: 18,
        chapter: 27,
        verse: 1,
      },
    ],
  },
  {
    keywords: [
      "grief",
      "grieving",
      "mourning",
      "heartbroken",
      "heartbreak",
      "broken heart",
      "loss",
      "losing",
    ],
    verses: [
      {
        ref: "Psalm 34:18",
        text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.",
        bookIndex: 18,
        chapter: 34,
        verse: 18,
      },
      {
        ref: "Matthew 5:4",
        text: "Blessed are they that mourn: for they shall be comforted.",
        bookIndex: 39,
        chapter: 5,
        verse: 4,
      },
      {
        ref: "Revelation 21:4",
        text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain.",
        bookIndex: 65,
        chapter: 21,
        verse: 4,
      },
    ],
  },
  {
    keywords: ["peace", "peaceful", "calm", "stillness", "still", "quiet", "serenity"],
    verses: [
      {
        ref: "Isaiah 26:3",
        text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
        bookIndex: 22,
        chapter: 26,
        verse: 3,
      },
      {
        ref: "John 14:27",
        text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
        bookIndex: 42,
        chapter: 14,
        verse: 27,
      },
      {
        ref: "Psalm 46:10",
        text: "Be still, and know that I am God.",
        bookIndex: 18,
        chapter: 46,
        verse: 10,
      },
    ],
  },
  {
    keywords: [
      "strength",
      "strong",
      "weak",
      "weakness",
      "weary",
      "tired",
      "exhausted",
      "worn out",
      "drained",
    ],
    verses: [
      {
        ref: "Isaiah 40:31",
        text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; they shall walk, and not faint.",
        bookIndex: 22,
        chapter: 40,
        verse: 31,
      },
      {
        ref: "Philippians 4:13",
        text: "I can do all things through Christ which strengtheneth me.",
        bookIndex: 49,
        chapter: 4,
        verse: 13,
      },
      {
        ref: "Psalm 28:7",
        text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped.",
        bookIndex: 18,
        chapter: 28,
        verse: 7,
      },
    ],
  },
  {
    keywords: [
      "hope",
      "hopeless",
      "hopelessness",
      "despair",
      "desperate",
      "give up",
      "giving up",
      "no way out",
    ],
    verses: [
      {
        ref: "Jeremiah 29:11",
        text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.",
        bookIndex: 23,
        chapter: 29,
        verse: 11,
      },
      {
        ref: "Romans 8:28",
        text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
        bookIndex: 44,
        chapter: 8,
        verse: 28,
      },
      {
        ref: "Psalm 31:24",
        text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.",
        bookIndex: 18,
        chapter: 31,
        verse: 24,
      },
    ],
  },
  {
    keywords: [
      "forgiveness",
      "forgive",
      "unforgiveness",
      "resentment",
      "bitter",
      "bitterness",
      "offended",
      "hurt by someone",
    ],
    verses: [
      {
        ref: "Ephesians 4:32",
        text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
        bookIndex: 48,
        chapter: 4,
        verse: 32,
      },
      {
        ref: "Matthew 6:14",
        text: "For if ye forgive men their trespasses, your heavenly Father will also forgive you.",
        bookIndex: 39,
        chapter: 6,
        verse: 14,
      },
      {
        ref: "Colossians 3:13",
        text: "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.",
        bookIndex: 50,
        chapter: 3,
        verse: 13,
      },
    ],
  },
  {
    keywords: ["faith", "believe", "belief", "doubt", "doubting", "uncertain", "unbelief"],
    verses: [
      {
        ref: "Hebrews 11:1",
        text: "Now faith is the substance of things hoped for, the evidence of things not seen.",
        bookIndex: 57,
        chapter: 11,
        verse: 1,
      },
      {
        ref: "Mark 9:24",
        text: "Lord, I believe; help thou mine unbelief.",
        bookIndex: 40,
        chapter: 9,
        verse: 24,
      },
      {
        ref: "Matthew 17:20",
        text: "If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.",
        bookIndex: 39,
        chapter: 17,
        verse: 20,
      },
    ],
  },
  {
    keywords: [
      "lonely",
      "loneliness",
      "alone",
      "isolated",
      "abandoned",
      "unloved",
      "rejection",
      "rejected",
    ],
    verses: [
      {
        ref: "Romans 8:39",
        text: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.",
        bookIndex: 44,
        chapter: 8,
        verse: 39,
      },
      {
        ref: "Deuteronomy 31:6",
        text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.",
        bookIndex: 4,
        chapter: 31,
        verse: 6,
      },
      {
        ref: "Psalm 68:6",
        text: "God setteth the solitary in families.",
        bookIndex: 18,
        chapter: 68,
        verse: 6,
      },
    ],
  },
  {
    keywords: [
      "direction",
      "purpose",
      "calling",
      "path",
      "lost",
      "confused",
      "which way",
      "guidance",
      "guide",
      "what should i do",
    ],
    verses: [
      {
        ref: "Proverbs 3:5",
        text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
        bookIndex: 19,
        chapter: 3,
        verse: 5,
      },
      {
        ref: "Psalm 32:8",
        text: "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.",
        bookIndex: 18,
        chapter: 32,
        verse: 8,
      },
      {
        ref: "Isaiah 30:21",
        text: "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it.",
        bookIndex: 22,
        chapter: 30,
        verse: 21,
      },
    ],
  },
  {
    keywords: [
      "joy",
      "happy",
      "happiness",
      "rejoice",
      "celebration",
      "celebrate",
      "thankful",
      "grateful",
      "gratitude",
    ],
    verses: [
      {
        ref: "Nehemiah 8:10",
        text: "The joy of the LORD is your strength.",
        bookIndex: 15,
        chapter: 8,
        verse: 10,
      },
      {
        ref: "Psalm 118:24",
        text: "This is the day which the LORD hath made; we will rejoice and be glad in it.",
        bookIndex: 18,
        chapter: 118,
        verse: 24,
      },
      {
        ref: "Philippians 4:4",
        text: "Rejoice in the Lord alway: and again I say, Rejoice.",
        bookIndex: 49,
        chapter: 4,
        verse: 4,
      },
    ],
  },
  {
    keywords: [
      "healing",
      "heal",
      "sick",
      "illness",
      "disease",
      "health",
      "pain",
      "suffering",
      "recovery",
      "hospital",
    ],
    verses: [
      {
        ref: "Jeremiah 17:14",
        text: "Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for thou art my praise.",
        bookIndex: 23,
        chapter: 17,
        verse: 14,
      },
      {
        ref: "1 Peter 2:24",
        text: "By whose stripes ye were healed.",
        bookIndex: 59,
        chapter: 2,
        verse: 24,
      },
      {
        ref: "Psalm 103:3",
        text: "Who forgiveth all thine iniquities; who healeth all thy diseases.",
        bookIndex: 18,
        chapter: 103,
        verse: 3,
      },
    ],
  },
  {
    keywords: [
      "marriage",
      "husband",
      "wife",
      "spouse",
      "relationship",
      "couple",
      "divorce",
      "separation",
      "reconciliation",
    ],
    verses: [
      {
        ref: "Ecclesiastes 4:9",
        text: "Two are better than one; because they have a good reward for their labour.",
        bookIndex: 20,
        chapter: 4,
        verse: 9,
      },
      {
        ref: "1 Corinthians 13:4",
        text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.",
        bookIndex: 45,
        chapter: 13,
        verse: 4,
      },
      {
        ref: "Proverbs 18:22",
        text: "Whoso findeth a wife findeth a good thing, and obtaineth favour of the LORD.",
        bookIndex: 19,
        chapter: 18,
        verse: 22,
      },
    ],
  },
  {
    keywords: [
      "children",
      "child",
      "parenting",
      "parent",
      "son",
      "daughter",
      "family",
      "kids",
      "motherhood",
      "fatherhood",
    ],
    verses: [
      {
        ref: "Proverbs 22:6",
        text: "Train up a child in the way he should go: and when he is old, he will not depart from it.",
        bookIndex: 19,
        chapter: 22,
        verse: 6,
      },
      {
        ref: "Psalm 127:3",
        text: "Lo, children are an heritage of the LORD: and the fruit of the womb is his reward.",
        bookIndex: 18,
        chapter: 127,
        verse: 3,
      },
      {
        ref: "Ephesians 6:4",
        text: "Bring them up in the nurture and admonition of the Lord.",
        bookIndex: 48,
        chapter: 6,
        verse: 4,
      },
    ],
  },
  {
    keywords: [
      "money",
      "finances",
      "financial",
      "debt",
      "broke",
      "poverty",
      "provision",
      "provide",
      "bills",
      "need",
      "lack",
    ],
    verses: [
      {
        ref: "Philippians 4:19",
        text: "But my God shall supply all your need according to his riches in glory by Christ Jesus.",
        bookIndex: 49,
        chapter: 4,
        verse: 19,
      },
      {
        ref: "Matthew 6:33",
        text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
        bookIndex: 39,
        chapter: 6,
        verse: 33,
      },
      {
        ref: "Proverbs 10:22",
        text: "The blessing of the LORD, it maketh rich, and he addeth no sorrow with it.",
        bookIndex: 19,
        chapter: 10,
        verse: 22,
      },
    ],
  },
  {
    keywords: ["anger", "angry", "rage", "furious", "frustration", "frustrated", "upset", "mad"],
    verses: [
      {
        ref: "Ephesians 4:26",
        text: "Be ye angry, and sin not: let not the sun go down upon your wrath.",
        bookIndex: 48,
        chapter: 4,
        verse: 26,
      },
      {
        ref: "Proverbs 15:1",
        text: "A soft answer turneth away wrath: but grievous words stir up anger.",
        bookIndex: 19,
        chapter: 15,
        verse: 1,
      },
      {
        ref: "James 1:19",
        text: "Let every man be swift to hear, slow to speak, slow to wrath.",
        bookIndex: 58,
        chapter: 1,
        verse: 19,
      },
    ],
  },
  {
    keywords: ["patience", "patient", "waiting", "wait", "delayed", "slow", "not yet"],
    verses: [
      {
        ref: "Psalm 27:14",
        text: "Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.",
        bookIndex: 18,
        chapter: 27,
        verse: 14,
      },
      {
        ref: "Romans 8:25",
        text: "But if we hope for that we see not, then do we with patience wait for it.",
        bookIndex: 44,
        chapter: 8,
        verse: 25,
      },
      {
        ref: "Galatians 6:9",
        text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
        bookIndex: 47,
        chapter: 6,
        verse: 9,
      },
    ],
  },
  {
    keywords: [
      "temptation",
      "tempted",
      "sin",
      "struggle",
      "addiction",
      "habit",
      "flesh",
      "lust",
      "falling",
    ],
    verses: [
      {
        ref: "1 Corinthians 10:13",
        text: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able.",
        bookIndex: 45,
        chapter: 10,
        verse: 13,
      },
      {
        ref: "James 4:7",
        text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
        bookIndex: 58,
        chapter: 4,
        verse: 7,
      },
      {
        ref: "Romans 8:1",
        text: "There is therefore now no condemnation to them which are in Christ Jesus.",
        bookIndex: 44,
        chapter: 8,
        verse: 1,
      },
    ],
  },
  {
    keywords: [
      "leadership",
      "leader",
      "ministry",
      "serve",
      "service",
      "calling",
      "vision",
      "mission",
    ],
    verses: [
      {
        ref: "Mark 10:45",
        text: "For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many.",
        bookIndex: 40,
        chapter: 10,
        verse: 45,
      },
      {
        ref: "Proverbs 29:18",
        text: "Where there is no vision, the people perish: but he that keepeth the law, happy is he.",
        bookIndex: 19,
        chapter: 29,
        verse: 18,
      },
      {
        ref: "1 Timothy 4:12",
        text: "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity.",
        bookIndex: 53,
        chapter: 4,
        verse: 12,
      },
    ],
  },
  {
    keywords: [
      "wisdom",
      "discernment",
      "decision",
      "decide",
      "knowledge",
      "understanding",
      "should i",
      "which choice",
    ],
    verses: [
      {
        ref: "James 1:5",
        text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
        bookIndex: 58,
        chapter: 1,
        verse: 5,
      },
      {
        ref: "Proverbs 4:7",
        text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.",
        bookIndex: 19,
        chapter: 4,
        verse: 7,
      },
      {
        ref: "Psalm 111:10",
        text: "The fear of the LORD is the beginning of wisdom: a good understanding have all they that do his commandments.",
        bookIndex: 18,
        chapter: 111,
        verse: 10,
      },
    ],
  },
  {
    keywords: [
      "protection",
      "protect",
      "safe",
      "safety",
      "danger",
      "enemy",
      "enemies",
      "attack",
      "threat",
    ],
    verses: [
      {
        ref: "Psalm 91:1",
        text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.",
        bookIndex: 18,
        chapter: 91,
        verse: 1,
      },
      {
        ref: "Isaiah 54:17",
        text: "No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn.",
        bookIndex: 22,
        chapter: 54,
        verse: 17,
      },
      {
        ref: "Psalm 46:1",
        text: "God is our refuge and strength, a very present help in trouble.",
        bookIndex: 18,
        chapter: 46,
        verse: 1,
      },
    ],
  },
  {
    keywords: [
      "prayer",
      "pray",
      "intercession",
      "intercede",
      "talking to god",
      "hear me",
      "does god hear",
    ],
    verses: [
      {
        ref: "Matthew 7:7",
        text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.",
        bookIndex: 39,
        chapter: 7,
        verse: 7,
      },
      {
        ref: "1 Thessalonians 5:17",
        text: "Pray without ceasing.",
        bookIndex: 51,
        chapter: 5,
        verse: 17,
      },
      {
        ref: "Jeremiah 33:3",
        text: "Call unto me, and I will answer thee, and show thee great and mighty things, which thou knowest not.",
        bookIndex: 23,
        chapter: 33,
        verse: 3,
      },
    ],
  },
  {
    keywords: ["work", "career", "job", "business", "success", "promotion", "opportunity", "favor"],
    verses: [
      {
        ref: "Colossians 3:23",
        text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
        bookIndex: 50,
        chapter: 3,
        verse: 23,
      },
      {
        ref: "Psalm 90:17",
        text: "Let the beauty of the LORD our God be upon us: and establish thou the work of our hands upon us.",
        bookIndex: 18,
        chapter: 90,
        verse: 17,
      },
      {
        ref: "Deuteronomy 28:12",
        text: "The LORD shall open unto thee his good treasure, the heaven to give the rain unto thy land in his season, and to bless all the work of thine hand.",
        bookIndex: 4,
        chapter: 28,
        verse: 12,
      },
    ],
  },
  {
    keywords: [
      "new beginning",
      "fresh start",
      "new season",
      "change",
      "transition",
      "starting over",
      "new chapter",
    ],
    verses: [
      {
        ref: "Isaiah 43:19",
        text: "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert.",
        bookIndex: 22,
        chapter: 43,
        verse: 19,
      },
      {
        ref: "Lamentations 3:23",
        text: "They are new every morning: great is thy faithfulness.",
        bookIndex: 24,
        chapter: 3,
        verse: 23,
      },
      {
        ref: "2 Corinthians 5:17",
        text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
        bookIndex: 46,
        chapter: 5,
        verse: 17,
      },
    ],
  },
  {
    keywords: ["praise", "worship", "glorify", "honor god", "praise god"],
    verses: [
      {
        ref: "Psalm 150:6",
        text: "Let every thing that hath breath praise the LORD. Praise ye the LORD.",
        bookIndex: 18,
        chapter: 150,
        verse: 6,
      },
      {
        ref: "Psalm 34:1",
        text: "I will bless the LORD at all times: his praise shall continually be in my mouth.",
        bookIndex: 18,
        chapter: 34,
        verse: 1,
      },
      {
        ref: "Hebrews 13:15",
        text: "By him therefore let us offer the sacrifice of praise to God continually, that is, the fruit of our lips giving thanks to his name.",
        bookIndex: 57,
        chapter: 13,
        verse: 15,
      },
    ],
  },
  {
    keywords: [
      "shame",
      "ashamed",
      "guilt",
      "guilty",
      "regret",
      "mistakes",
      "past",
      "what i did",
      "embarrassed",
    ],
    verses: [
      {
        ref: "Romans 8:1",
        text: "There is therefore now no condemnation to them which are in Christ Jesus.",
        bookIndex: 44,
        chapter: 8,
        verse: 1,
      },
      {
        ref: "1 John 1:9",
        text: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.",
        bookIndex: 61,
        chapter: 1,
        verse: 9,
      },
      {
        ref: "Isaiah 43:25",
        text: "I, even I, am he that blotteth out thy transgressions for mine own sake, and will not remember thy sins.",
        bookIndex: 22,
        chapter: 43,
        verse: 25,
      },
    ],
  },
  {
    keywords: [
      "identity",
      "who am i",
      "self worth",
      "value",
      "worth",
      "insignificant",
      "not enough",
      "inadequate",
    ],
    verses: [
      {
        ref: "Psalm 139:14",
        text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works.",
        bookIndex: 18,
        chapter: 139,
        verse: 14,
      },
      {
        ref: "1 Peter 2:9",
        text: "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people.",
        bookIndex: 59,
        chapter: 2,
        verse: 9,
      },
      {
        ref: "Ephesians 2:10",
        text: "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.",
        bookIndex: 48,
        chapter: 2,
        verse: 10,
      },
    ],
  },
  {
    keywords: [
      "courage",
      "courageous",
      "brave",
      "bravery",
      "step out",
      "bold",
      "boldness",
      "move forward",
    ],
    verses: [
      {
        ref: "Joshua 1:9",
        text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
        bookIndex: 5,
        chapter: 1,
        verse: 9,
      },
      {
        ref: "Isaiah 41:13",
        text: "For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.",
        bookIndex: 22,
        chapter: 41,
        verse: 13,
      },
      {
        ref: "Psalm 138:3",
        text: "In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul.",
        bookIndex: 18,
        chapter: 138,
        verse: 3,
      },
    ],
  },
  {
    keywords: [
      "depression",
      "depressed",
      "sad",
      "sadness",
      "dark",
      "darkness",
      "heavy",
      "heaviness",
      "down",
      "low",
    ],
    verses: [
      {
        ref: "Psalm 30:5",
        text: "Weeping may endure for a night, but joy cometh in the morning.",
        bookIndex: 18,
        chapter: 30,
        verse: 5,
      },
      {
        ref: "Matthew 11:28",
        text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
        bookIndex: 39,
        chapter: 11,
        verse: 28,
      },
      {
        ref: "Psalm 42:11",
        text: "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him.",
        bookIndex: 18,
        chapter: 42,
        verse: 11,
      },
    ],
  },
  {
    keywords: [
      "trust god",
      "trusting",
      "let go",
      "surrender",
      "control",
      "release",
      "give it to god",
    ],
    verses: [
      {
        ref: "Proverbs 3:5",
        text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.",
        bookIndex: 19,
        chapter: 3,
        verse: 5,
      },
      {
        ref: "Psalm 37:5",
        text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.",
        bookIndex: 18,
        chapter: 37,
        verse: 5,
      },
      {
        ref: "Isaiah 26:4",
        text: "Trust ye in the LORD for ever: for in the LORD JEHOVAH is everlasting strength.",
        bookIndex: 22,
        chapter: 26,
        verse: 4,
      },
    ],
  },
  {
    keywords: [
      "obedience",
      "obey",
      "disobedience",
      "commandments",
      "follow god",
      "discipline",
      "correction",
    ],
    verses: [
      {
        ref: "John 14:15",
        text: "If ye love me, keep my commandments.",
        bookIndex: 42,
        chapter: 14,
        verse: 15,
      },
      {
        ref: "1 Samuel 15:22",
        text: "Behold, to obey is better than sacrifice, and to hearken than the fat of rams.",
        bookIndex: 8,
        chapter: 15,
        verse: 22,
      },
      {
        ref: "Deuteronomy 28:1",
        text: "If thou shalt hearken diligently unto the voice of the LORD thy God, to observe and to do all his commandments, that the LORD thy God will set thee on high above all nations of the earth.",
        bookIndex: 4,
        chapter: 28,
        verse: 1,
      },
    ],
  },
  {
    keywords: [
      "salvation",
      "saved",
      "born again",
      "eternal life",
      "heaven",
      "redemption",
      "redeemed",
    ],
    verses: [
      {
        ref: "John 3:16",
        text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
        bookIndex: 42,
        chapter: 3,
        verse: 16,
      },
      {
        ref: "Romans 10:9",
        text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.",
        bookIndex: 44,
        chapter: 10,
        verse: 9,
      },
      {
        ref: "Acts 4:12",
        text: "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.",
        bookIndex: 43,
        chapter: 4,
        verse: 12,
      },
    ],
  },
  {
    keywords: [
      "breakthrough",
      "victory",
      "overcome",
      "overcoming",
      "winning",
      "triumph",
      "conquer",
    ],
    verses: [
      {
        ref: "1 John 5:4",
        text: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith.",
        bookIndex: 61,
        chapter: 5,
        verse: 4,
      },
      {
        ref: "Romans 8:37",
        text: "Nay, in all these things we are more than conquerors through him that loved us.",
        bookIndex: 44,
        chapter: 8,
        verse: 37,
      },
      {
        ref: "Deuteronomy 20:4",
        text: "For the LORD your God is he that goeth with you, to fight for you against your enemies, to save you.",
        bookIndex: 4,
        chapter: 20,
        verse: 4,
      },
    ],
  },
  {
    keywords: ["love", "loving", "love of god", "feel loved", "god loves me"],
    verses: [
      {
        ref: "1 John 4:10",
        text: "Herein is love, not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins.",
        bookIndex: 61,
        chapter: 4,
        verse: 10,
      },
      {
        ref: "Romans 5:8",
        text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
        bookIndex: 44,
        chapter: 5,
        verse: 8,
      },
      {
        ref: "Jeremiah 31:3",
        text: "Yea, I have loved thee with an everlasting love.",
        bookIndex: 23,
        chapter: 31,
        verse: 3,
      },
    ],
  },
  {
    keywords: [
      "unity",
      "community",
      "church",
      "together",
      "body of christ",
      "fellowship",
      "division",
      "conflict",
    ],
    verses: [
      {
        ref: "Psalm 133:1",
        text: "Behold, how good and how pleasant it is for brethren to dwell together in unity!",
        bookIndex: 18,
        chapter: 133,
        verse: 1,
      },
      {
        ref: "Romans 12:16",
        text: "Be of the same mind one toward another.",
        bookIndex: 44,
        chapter: 12,
        verse: 16,
      },
      {
        ref: "Ephesians 4:3",
        text: "Endeavouring to keep the unity of the Spirit in the bond of peace.",
        bookIndex: 48,
        chapter: 4,
        verse: 3,
      },
    ],
  },
  {
    keywords: ["generosity", "giving", "tithe", "offering", "sowing", "seed", "give"],
    verses: [
      {
        ref: "2 Corinthians 9:7",
        text: "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.",
        bookIndex: 46,
        chapter: 9,
        verse: 7,
      },
      {
        ref: "Luke 6:38",
        text: "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom.",
        bookIndex: 41,
        chapter: 6,
        verse: 38,
      },
      {
        ref: "Proverbs 11:25",
        text: "The liberal soul shall be made fat: and he that watereth shall be watered also himself.",
        bookIndex: 19,
        chapter: 11,
        verse: 25,
      },
    ],
  },
  {
    keywords: ["humility", "humble", "pride", "arrogance", "ego", "put others first"],
    verses: [
      {
        ref: "Proverbs 11:2",
        text: "When pride cometh, then cometh shame: but with the lowly is wisdom.",
        bookIndex: 19,
        chapter: 11,
        verse: 2,
      },
      {
        ref: "James 4:10",
        text: "Humble yourselves in the sight of the Lord, and he shall lift you up.",
        bookIndex: 58,
        chapter: 4,
        verse: 10,
      },
      {
        ref: "Philippians 2:3",
        text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves.",
        bookIndex: 49,
        chapter: 2,
        verse: 3,
      },
    ],
  },
  {
    keywords: [
      "restoration",
      "restore",
      "rebuild",
      "repair",
      "broken",
      "ruined",
      "failed",
      "failure",
    ],
    verses: [
      {
        ref: "Joel 2:25",
        text: "And I will restore to you the years that the locust hath eaten.",
        bookIndex: 28,
        chapter: 2,
        verse: 25,
      },
      {
        ref: "Psalm 23:3",
        text: "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
        bookIndex: 18,
        chapter: 23,
        verse: 3,
      },
      {
        ref: "Isaiah 61:7",
        text: "For your shame ye shall have double; and for confusion they shall rejoice in their portion.",
        bookIndex: 22,
        chapter: 61,
        verse: 7,
      },
    ],
  },
  {
    keywords: [
      "death",
      "dying",
      "funeral",
      "end of life",
      "passed away",
      "someone died",
      "losing someone",
    ],
    verses: [
      {
        ref: "John 11:25",
        text: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.",
        bookIndex: 42,
        chapter: 11,
        verse: 25,
      },
      {
        ref: "Psalm 23:4",
        text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me.",
        bookIndex: 18,
        chapter: 23,
        verse: 4,
      },
      {
        ref: "1 Thessalonians 4:14",
        text: "For if we believe that Jesus died and rose again, even so them also which sleep in Jesus will God bring with him.",
        bookIndex: 51,
        chapter: 4,
        verse: 14,
      },
    ],
  },
  {
    keywords: ["word of god", "bible", "scripture", "the word", "truth", "studying", "study bible"],
    verses: [
      {
        ref: "2 Timothy 3:16",
        text: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.",
        bookIndex: 54,
        chapter: 3,
        verse: 16,
      },
      {
        ref: "Psalm 119:105",
        text: "Thy word is a lamp unto my feet, and a light unto my path.",
        bookIndex: 18,
        chapter: 119,
        verse: 105,
      },
      {
        ref: "Hebrews 4:12",
        text: "For the word of God is quick, and powerful, and sharper than any twoedged sword.",
        bookIndex: 57,
        chapter: 4,
        verse: 12,
      },
    ],
  },
  {
    keywords: [
      "holy spirit",
      "spirit",
      "anointing",
      "anointed",
      "fire",
      "fill me",
      "presence of god",
      "move of god",
    ],
    verses: [
      {
        ref: "Acts 1:8",
        text: "But ye shall receive power, after that the Holy Ghost is come upon you.",
        bookIndex: 43,
        chapter: 1,
        verse: 8,
      },
      {
        ref: "John 14:26",
        text: "But the Comforter, which is the Holy Ghost, whom the Father will send in my name, he shall teach you all things.",
        bookIndex: 42,
        chapter: 14,
        verse: 26,
      },
      {
        ref: "Romans 8:26",
        text: "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us.",
        bookIndex: 44,
        chapter: 8,
        verse: 26,
      },
    ],
  },
  {
    keywords: [
      "miracle",
      "miracles",
      "supernatural",
      "impossible",
      "nothing is impossible",
      "believe for",
    ],
    verses: [
      {
        ref: "Luke 1:37",
        text: "For with God nothing shall be impossible.",
        bookIndex: 41,
        chapter: 1,
        verse: 37,
      },
      {
        ref: "Mark 9:23",
        text: "If thou canst believe, all things are possible to him that believeth.",
        bookIndex: 40,
        chapter: 9,
        verse: 23,
      },
      {
        ref: "Jeremiah 32:27",
        text: "Behold, I am the LORD, the God of all flesh: is there any thing too hard for me?",
        bookIndex: 23,
        chapter: 32,
        verse: 27,
      },
    ],
  },
  {
    keywords: ["morning", "today", "this day", "fresh", "start the day", "waking up", "new day"],
    verses: [
      {
        ref: "Lamentations 3:23",
        text: "They are new every morning: great is thy faithfulness.",
        bookIndex: 24,
        chapter: 3,
        verse: 23,
      },
      {
        ref: "Psalm 118:24",
        text: "This is the day which the LORD hath made; we will rejoice and be glad in it.",
        bookIndex: 18,
        chapter: 118,
        verse: 24,
      },
      {
        ref: "Psalm 5:3",
        text: "My voice shalt thou hear in the morning, O LORD; in the morning will I direct my prayer unto thee, and will look up.",
        bookIndex: 18,
        chapter: 5,
        verse: 3,
      },
    ],
  },
  {
    keywords: ["night", "evening", "sleep", "rest", "insomnia", "can't sleep", "awake at night"],
    verses: [
      {
        ref: "Psalm 4:8",
        text: "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.",
        bookIndex: 18,
        chapter: 4,
        verse: 8,
      },
      {
        ref: "Psalm 121:4",
        text: "Behold, he that keepeth Israel shall neither slumber nor sleep.",
        bookIndex: 18,
        chapter: 121,
        verse: 4,
      },
      {
        ref: "Proverbs 3:24",
        text: "When thou liest down, thou shalt not be afraid: yea, thou shalt lie down, and thy sleep shall be sweet.",
        bookIndex: 19,
        chapter: 3,
        verse: 24,
      },
    ],
  },
  {
    keywords: ["friendship", "friend", "friends", "betrayal", "betrayed", "backstabbed"],
    verses: [
      {
        ref: "Proverbs 17:17",
        text: "A friend loveth at all times, and a brother is born for adversity.",
        bookIndex: 19,
        chapter: 17,
        verse: 17,
      },
      {
        ref: "John 15:13",
        text: "Greater love hath no man than this, that a man lay down his life for his friends.",
        bookIndex: 42,
        chapter: 15,
        verse: 13,
      },
      {
        ref: "Proverbs 18:24",
        text: "There is a friend that sticketh closer than a brother.",
        bookIndex: 19,
        chapter: 18,
        verse: 24,
      },
    ],
  },
  {
    keywords: [
      "spiritual warfare",
      "warfare",
      "battle",
      "spiritual battle",
      "fight",
      "stand firm",
      "armor",
    ],
    verses: [
      {
        ref: "Ephesians 6:11",
        text: "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.",
        bookIndex: 48,
        chapter: 6,
        verse: 11,
      },
      {
        ref: "2 Corinthians 10:4",
        text: "For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds.",
        bookIndex: 46,
        chapter: 10,
        verse: 4,
      },
      {
        ref: "1 Peter 5:8",
        text: "Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour.",
        bookIndex: 59,
        chapter: 5,
        verse: 8,
      },
    ],
  },
  {
    keywords: ["abundance", "overflow", "more than enough", "blessed", "blessing", "blessings"],
    verses: [
      {
        ref: "John 10:10",
        text: "I am come that they might have life, and that they might have it more abundantly.",
        bookIndex: 42,
        chapter: 10,
        verse: 10,
      },
      {
        ref: "Psalm 23:5",
        text: "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.",
        bookIndex: 18,
        chapter: 23,
        verse: 5,
      },
      {
        ref: "Malachi 3:10",
        text: "Prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it.",
        bookIndex: 38,
        chapter: 3,
        verse: 10,
      },
    ],
  },
  {
    keywords: [
      "season",
      "waiting season",
      "dry season",
      "difficult season",
      "wilderness",
      "in between",
    ],
    verses: [
      {
        ref: "Ecclesiastes 3:1",
        text: "To every thing there is a season, and a time to every purpose under the heaven.",
        bookIndex: 20,
        chapter: 3,
        verse: 1,
      },
      {
        ref: "Isaiah 43:2",
        text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee.",
        bookIndex: 22,
        chapter: 43,
        verse: 2,
      },
      {
        ref: "Hosea 2:14",
        text: "Therefore, behold, I will allure her, and bring her into the wilderness, and speak comfortably unto her.",
        bookIndex: 27,
        chapter: 2,
        verse: 14,
      },
    ],
  },
  {
    keywords: [
      "future",
      "tomorrow",
      "what will happen",
      "unknown",
      "uncertainty",
      "anxiety about the future",
    ],
    verses: [
      {
        ref: "Matthew 6:34",
        text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.",
        bookIndex: 39,
        chapter: 6,
        verse: 34,
      },
      {
        ref: "Proverbs 19:21",
        text: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.",
        bookIndex: 19,
        chapter: 19,
        verse: 21,
      },
      {
        ref: "Isaiah 46:10",
        text: "Declaring the end from the beginning, and from ancient times the things that are not yet done, saying, My counsel shall stand.",
        bookIndex: 22,
        chapter: 46,
        verse: 10,
      },
    ],
  },
  {
    keywords: [
      "persecution",
      "persecuted",
      "hated",
      "mistreated",
      "unfair",
      "injustice",
      "treated badly",
    ],
    verses: [
      {
        ref: "Matthew 5:10",
        text: "Blessed are they which are persecuted for righteousness' sake: for theirs is the kingdom of heaven.",
        bookIndex: 39,
        chapter: 5,
        verse: 10,
      },
      {
        ref: "Romans 8:31",
        text: "If God be for us, who can be against us?",
        bookIndex: 44,
        chapter: 8,
        verse: 31,
      },
      {
        ref: "Isaiah 41:10",
        text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God.",
        bookIndex: 22,
        chapter: 41,
        verse: 10,
      },
    ],
  },
  {
    keywords: [
      "focus",
      "distracted",
      "distraction",
      "goals",
      "discipline",
      "stay on track",
      "productivity",
    ],
    verses: [
      {
        ref: "Philippians 3:14",
        text: "I press toward the mark for the prize of the high calling of God in Christ Jesus.",
        bookIndex: 49,
        chapter: 3,
        verse: 14,
      },
      {
        ref: "Hebrews 12:1",
        text: "Let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us.",
        bookIndex: 57,
        chapter: 12,
        verse: 1,
      },
      {
        ref: "Proverbs 4:25",
        text: "Let thine eyes look right on, and let thine eyelids look straight before thee.",
        bookIndex: 19,
        chapter: 4,
        verse: 25,
      },
    ],
  },
  {
    keywords: [
      "contentment",
      "content",
      "enough",
      "satisfied",
      "discontented",
      "wanting more",
      "envy",
      "jealousy",
      "jealous",
    ],
    verses: [
      {
        ref: "Philippians 4:11",
        text: "I have learned, in whatsoever state I am, therewith to be content.",
        bookIndex: 49,
        chapter: 4,
        verse: 11,
      },
      {
        ref: "1 Timothy 6:6",
        text: "But godliness with contentment is great gain.",
        bookIndex: 53,
        chapter: 6,
        verse: 6,
      },
      {
        ref: "Hebrews 13:5",
        text: "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee.",
        bookIndex: 57,
        chapter: 13,
        verse: 5,
      },
    ],
  },
  {
    keywords: [
      "repentance",
      "repent",
      "turn back",
      "backsliding",
      "backslider",
      "strayed",
      "prodigal",
      "returning",
    ],
    verses: [
      {
        ref: "2 Chronicles 7:14",
        text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin.",
        bookIndex: 13,
        chapter: 7,
        verse: 14,
      },
      {
        ref: "Luke 15:20",
        text: "And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him.",
        bookIndex: 41,
        chapter: 15,
        verse: 20,
      },
      {
        ref: "Hosea 14:4",
        text: "I will heal their backsliding, I will love them freely: for mine anger is turned away from him.",
        bookIndex: 27,
        chapter: 14,
        verse: 4,
      },
    ],
  },
  {
    keywords: ["education", "school", "learning", "student", "exam", "test", "studying hard"],
    verses: [
      {
        ref: "Daniel 1:17",
        text: "As for these four children, God gave them knowledge and skill in all learning and wisdom.",
        bookIndex: 26,
        chapter: 1,
        verse: 17,
      },
      {
        ref: "Proverbs 2:6",
        text: "For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding.",
        bookIndex: 19,
        chapter: 2,
        verse: 6,
      },
      {
        ref: "Ecclesiastes 7:12",
        text: "The excellency of knowledge is, that wisdom giveth life to them that have it.",
        bookIndex: 20,
        chapter: 7,
        verse: 12,
      },
    ],
  },
  {
    keywords: [
      "nation",
      "country",
      "government",
      "politics",
      "leaders",
      "pray for leaders",
      "world",
    ],
    verses: [
      {
        ref: "2 Chronicles 7:14",
        text: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven.",
        bookIndex: 13,
        chapter: 7,
        verse: 14,
      },
      {
        ref: "Proverbs 14:34",
        text: "Righteousness exalteth a nation: but sin is a reproach to any people.",
        bookIndex: 19,
        chapter: 14,
        verse: 34,
      },
      {
        ref: "1 Timothy 2:2",
        text: "For kings, and for all that are in authority; that we may lead a quiet and peaceable life in all godliness and honesty.",
        bookIndex: 53,
        chapter: 2,
        verse: 2,
      },
    ],
  },
  {
    keywords: ["aging", "old", "growing old", "elderly", "grey hair", "years", "getting older"],
    verses: [
      {
        ref: "Psalm 92:14",
        text: "They shall still bring forth fruit in old age; they shall be fat and flourishing.",
        bookIndex: 18,
        chapter: 92,
        verse: 14,
      },
      {
        ref: "Proverbs 16:31",
        text: "The hoary head is a crown of glory, if it be found in the way of righteousness.",
        bookIndex: 19,
        chapter: 16,
        verse: 31,
      },
      {
        ref: "Isaiah 46:4",
        text: "And even to your old age I am he; and even to hoar hairs will I carry you: I have made, and I will bear; even I will carry, and will deliver you.",
        bookIndex: 22,
        chapter: 46,
        verse: 4,
      },
    ],
  },
];

export function matchFeelingToVerses(input: string): FeelingVerse[] | null {
  if (!input.trim()) return null;
  const lower = input.trim().toLowerCase();
  const scored = FEELING_MAP.map((entry) => ({
    entry,
    score: entry.keywords.reduce(
      (acc, kw) => (lower.includes(kw) ? acc + (kw.length > 5 ? 2 : 1) : acc),
      0,
    ),
  }))
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score);
  if (scored.length === 0) return null;
  return scored[0].entry.verses;
}

export function getAllMatchingVerses(input: string): FeelingVerse[] {
  if (!input.trim()) return [];
  const lower = input.trim().toLowerCase();
  const all: FeelingVerse[] = [];
  const seen = new Set<string>();
  FEELING_MAP.filter((entry) => entry.keywords.some((kw) => lower.includes(kw))).forEach((entry) =>
    entry.verses.forEach((v) => {
      if (!seen.has(v.ref)) {
        seen.add(v.ref);
        all.push(v);
      }
    }),
  );
  return all;
}

export function getVersesByCategory(category: string): FeelingVerse[] {
  if (!category.trim()) return [];
  const lower = category.trim().toLowerCase();
  const entry = FEELING_MAP.find((e) => e.keywords.some((kw) => kw.toLowerCase() === lower));
  return entry ? entry.verses : [];
}
