/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceSermonsRouteImport } from './routes/workspace.sermons'
import { Route as SettingsServiceModeRouteImport } from './routes/settings.service-mode'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsReadingRouteImport } from './routes/settings.reading'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsIntelligenceRouteImport } from './routes/settings.intelligence'
import { Route as SettingsCalendarSyncRouteImport } from './routes/settings.calendar-sync'
import { Route as ReaderPrintRouteImport } from './routes/reader.print'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AccountBoardRouteImport } from './routes/account_.board'
import { Route as AccountBillingRouteImport } from './routes/account_.billing'
import { Route as _devSpinnersRouteImport } from './routes/__dev.spinners'
import { Route as _devReaderDiagnosticsRouteImport } from './routes/__dev.reader-diagnostics'
import { Route as _devIosSafeAreaRouteImport } from './routes/__dev.ios-safe-area'
import { Route as _devBlueprintRouteImport } from './routes/__dev.blueprint'
import { Route as WorkspaceSermonsIndexRouteImport } from './routes/workspace.sermons.index'
import { Route as WorkspaceSermonsNewRouteImport } from './routes/workspace.sermons.new'
import { Route as WorkspaceSermonsChoiceRouteImport } from './routes/workspace.sermons.choice'
import { Route as WorkspaceSermonsSermonIdRouteImport } from './routes/workspace.sermons.$sermonId'
import { Route as ApiPublicSendPushRouteImport } from './routes/api.public.send-push'
import { Route as ApiPublicReaderVoiceEngineRouteImport } from './routes/api.public.reader-voice-engine'
import { Route as ApiPublicGoogleTtsHealthRouteImport } from './routes/api.public.google-tts-health'
import { Route as AccountBoardShareRouteImport } from './routes/account_.board.share'
import { Route as HooksCalendarTokenIcsRouteImport } from './routes/hooks.calendar.$token.ics'
import { Route as ApiPublicOgHandleRouteImport } from './routes/api.public.og.$handle'
import { Route as ApiPublicNotificationsMarkReadRouteImport } from './routes/api.public.notifications.mark-read'
import { Route as ApiPublicHooksSelahWeeklyRouteImport } from './routes/api.public.hooks.selah-weekly'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSermonsRoute = WorkspaceSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SettingsServiceModeRoute = SettingsServiceModeRouteImport.update({
  id: '/service-mode',
  path: '/service-mode',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsReadingRoute = SettingsReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntelligenceRoute = SettingsIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCalendarSyncRoute = SettingsCalendarSyncRouteImport.update({
  id: '/calendar-sync',
  path: '/calendar-sync',
  getParentRoute: () => SettingsRoute,
} as any)
const ReaderPrintRoute = ReaderPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => ReaderRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AccountBoardRoute = AccountBoardRouteImport.update({
  id: '/account_/board',
  path: '/account/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account_/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const _devSpinnersRoute = _devSpinnersRouteImport.update({
  id: '/__dev/spinners',
  path: '/spinners',
  getParentRoute: () => rootRouteImport,
} as any)
const _devReaderDiagnosticsRoute = _devReaderDiagnosticsRouteImport.update({
  id: '/__dev/reader-diagnostics',
  path: '/reader-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const _devIosSafeAreaRoute = _devIosSafeAreaRouteImport.update({
  id: '/__dev/ios-safe-area',
  path: '/ios-safe-area',
  getParentRoute: () => rootRouteImport,
} as any)
const _devBlueprintRoute = _devBlueprintRouteImport.update({
  id: '/__dev/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSermonsIndexRoute = WorkspaceSermonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSermonsRoute,
} as any)
const WorkspaceSermonsNewRoute = WorkspaceSermonsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspaceSermonsRoute,
} as any)
const WorkspaceSermonsChoiceRoute = WorkspaceSermonsChoiceRouteImport.update({
  id: '/choice',
  path: '/choice',
  getParentRoute: () => WorkspaceSermonsRoute,
} as any)
const WorkspaceSermonsSermonIdRoute =
  WorkspaceSermonsSermonIdRouteImport.update({
    id: '/$sermonId',
    path: '/$sermonId',
    getParentRoute: () => WorkspaceSermonsRoute,
  } as any)
const ApiPublicSendPushRoute = ApiPublicSendPushRouteImport.update({
  id: '/api/public/send-push',
  path: '/api/public/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReaderVoiceEngineRoute =
  ApiPublicReaderVoiceEngineRouteImport.update({
    id: '/api/public/reader-voice-engine',
    path: '/api/public/reader-voice-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleTtsHealthRoute =
  ApiPublicGoogleTtsHealthRouteImport.update({
    id: '/api/public/google-tts-health',
    path: '/api/public/google-tts-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountBoardShareRoute = AccountBoardShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AccountBoardRoute,
} as any)
const HooksCalendarTokenIcsRoute = HooksCalendarTokenIcsRouteImport.update({
  id: '/hooks/calendar/$token/ics',
  path: '/hooks/calendar/$token/ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgHandleRoute = ApiPublicOgHandleRouteImport.update({
  id: '/api/public/og/$handle',
  path: '/api/public/og/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsMarkReadRoute =
  ApiPublicNotificationsMarkReadRouteImport.update({
    id: '/api/public/notifications/mark-read',
    path: '/api/public/notifications/mark-read',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSelahWeeklyRoute =
  ApiPublicHooksSelahWeeklyRouteImport.update({
    id: '/api/public/hooks/selah-weekly',
    path: '/api/public/hooks/selah-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finances': typeof FinancesRoute
  '/journey': typeof JourneyRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reader': typeof ReaderRouteWithChildren
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/blueprint': typeof _devBlueprintRoute
  '/ios-safe-area': typeof _devIosSafeAreaRoute
  '/reader-diagnostics': typeof _devReaderDiagnosticsRoute
  '/spinners': typeof _devSpinnersRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/board': typeof AccountBoardRouteWithChildren
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/reader/print': typeof ReaderPrintRoute
  '/settings/calendar-sync': typeof SettingsCalendarSyncRoute
  '/settings/intelligence': typeof SettingsIntelligenceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/reading': typeof SettingsReadingRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/service-mode': typeof SettingsServiceModeRoute
  '/workspace/sermons': typeof WorkspaceSermonsRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/account/board/share': typeof AccountBoardShareRoute
  '/api/public/google-tts-health': typeof ApiPublicGoogleTtsHealthRoute
  '/api/public/reader-voice-engine': typeof ApiPublicReaderVoiceEngineRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/workspace/sermons/$sermonId': typeof WorkspaceSermonsSermonIdRoute
  '/workspace/sermons/choice': typeof WorkspaceSermonsChoiceRoute
  '/workspace/sermons/new': typeof WorkspaceSermonsNewRoute
  '/workspace/sermons/': typeof WorkspaceSermonsIndexRoute
  '/api/public/hooks/selah-weekly': typeof ApiPublicHooksSelahWeeklyRoute
  '/api/public/notifications/mark-read': typeof ApiPublicNotificationsMarkReadRoute
  '/api/public/og/$handle': typeof ApiPublicOgHandleRoute
  '/hooks/calendar/$token/ics': typeof HooksCalendarTokenIcsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finances': typeof FinancesRoute
  '/journey': typeof JourneyRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reader': typeof ReaderRouteWithChildren
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/blueprint': typeof _devBlueprintRoute
  '/ios-safe-area': typeof _devIosSafeAreaRoute
  '/reader-diagnostics': typeof _devReaderDiagnosticsRoute
  '/spinners': typeof _devSpinnersRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/board': typeof AccountBoardRouteWithChildren
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/reader/print': typeof ReaderPrintRoute
  '/settings/calendar-sync': typeof SettingsCalendarSyncRoute
  '/settings/intelligence': typeof SettingsIntelligenceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/reading': typeof SettingsReadingRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/service-mode': typeof SettingsServiceModeRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/account/board/share': typeof AccountBoardShareRoute
  '/api/public/google-tts-health': typeof ApiPublicGoogleTtsHealthRoute
  '/api/public/reader-voice-engine': typeof ApiPublicReaderVoiceEngineRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/workspace/sermons/$sermonId': typeof WorkspaceSermonsSermonIdRoute
  '/workspace/sermons/choice': typeof WorkspaceSermonsChoiceRoute
  '/workspace/sermons/new': typeof WorkspaceSermonsNewRoute
  '/workspace/sermons': typeof WorkspaceSermonsIndexRoute
  '/api/public/hooks/selah-weekly': typeof ApiPublicHooksSelahWeeklyRoute
  '/api/public/notifications/mark-read': typeof ApiPublicNotificationsMarkReadRoute
  '/api/public/og/$handle': typeof ApiPublicOgHandleRoute
  '/hooks/calendar/$token/ics': typeof HooksCalendarTokenIcsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finances': typeof FinancesRoute
  '/journey': typeof JourneyRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reader': typeof ReaderRouteWithChildren
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/__dev/blueprint': typeof _devBlueprintRoute
  '/__dev/ios-safe-area': typeof _devIosSafeAreaRoute
  '/__dev/reader-diagnostics': typeof _devReaderDiagnosticsRoute
  '/__dev/spinners': typeof _devSpinnersRoute
  '/account_/billing': typeof AccountBillingRoute
  '/account_/board': typeof AccountBoardRouteWithChildren
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/reader/print': typeof ReaderPrintRoute
  '/settings/calendar-sync': typeof SettingsCalendarSyncRoute
  '/settings/intelligence': typeof SettingsIntelligenceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/reading': typeof SettingsReadingRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/service-mode': typeof SettingsServiceModeRoute
  '/workspace/sermons': typeof WorkspaceSermonsRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/account_/board/share': typeof AccountBoardShareRoute
  '/api/public/google-tts-health': typeof ApiPublicGoogleTtsHealthRoute
  '/api/public/reader-voice-engine': typeof ApiPublicReaderVoiceEngineRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/workspace/sermons/$sermonId': typeof WorkspaceSermonsSermonIdRoute
  '/workspace/sermons/choice': typeof WorkspaceSermonsChoiceRoute
  '/workspace/sermons/new': typeof WorkspaceSermonsNewRoute
  '/workspace/sermons/': typeof WorkspaceSermonsIndexRoute
  '/api/public/hooks/selah-weekly': typeof ApiPublicHooksSelahWeeklyRoute
  '/api/public/notifications/mark-read': typeof ApiPublicNotificationsMarkReadRoute
  '/api/public/og/$handle': typeof ApiPublicOgHandleRoute
  '/hooks/calendar/$token/ics': typeof HooksCalendarTokenIcsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/finances'
    | '/journey'
    | '/notes'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/reader'
    | '/saved'
    | '/search'
    | '/settings'
    | '/terms'
    | '/vault'
    | '/workspace'
    | '/blueprint'
    | '/ios-safe-area'
    | '/reader-diagnostics'
    | '/spinners'
    | '/account/billing'
    | '/account/board'
    | '/admin/webhooks'
    | '/reader/print'
    | '/settings/calendar-sync'
    | '/settings/intelligence'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/reading'
    | '/settings/security'
    | '/settings/service-mode'
    | '/workspace/sermons'
    | '/workspace/'
    | '/account/board/share'
    | '/api/public/google-tts-health'
    | '/api/public/reader-voice-engine'
    | '/api/public/send-push'
    | '/workspace/sermons/$sermonId'
    | '/workspace/sermons/choice'
    | '/workspace/sermons/new'
    | '/workspace/sermons/'
    | '/api/public/hooks/selah-weekly'
    | '/api/public/notifications/mark-read'
    | '/api/public/og/$handle'
    | '/hooks/calendar/$token/ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/finances'
    | '/journey'
    | '/notes'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/reader'
    | '/saved'
    | '/search'
    | '/settings'
    | '/terms'
    | '/vault'
    | '/blueprint'
    | '/ios-safe-area'
    | '/reader-diagnostics'
    | '/spinners'
    | '/account/billing'
    | '/account/board'
    | '/admin/webhooks'
    | '/reader/print'
    | '/settings/calendar-sync'
    | '/settings/intelligence'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/reading'
    | '/settings/security'
    | '/settings/service-mode'
    | '/workspace'
    | '/account/board/share'
    | '/api/public/google-tts-health'
    | '/api/public/reader-voice-engine'
    | '/api/public/send-push'
    | '/workspace/sermons/$sermonId'
    | '/workspace/sermons/choice'
    | '/workspace/sermons/new'
    | '/workspace/sermons'
    | '/api/public/hooks/selah-weekly'
    | '/api/public/notifications/mark-read'
    | '/api/public/og/$handle'
    | '/hooks/calendar/$token/ics'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/finances'
    | '/journey'
    | '/notes'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/reader'
    | '/saved'
    | '/search'
    | '/settings'
    | '/terms'
    | '/vault'
    | '/workspace'
    | '/__dev/blueprint'
    | '/__dev/ios-safe-area'
    | '/__dev/reader-diagnostics'
    | '/__dev/spinners'
    | '/account_/billing'
    | '/account_/board'
    | '/admin/webhooks'
    | '/reader/print'
    | '/settings/calendar-sync'
    | '/settings/intelligence'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/reading'
    | '/settings/security'
    | '/settings/service-mode'
    | '/workspace/sermons'
    | '/workspace/'
    | '/account_/board/share'
    | '/api/public/google-tts-health'
    | '/api/public/reader-voice-engine'
    | '/api/public/send-push'
    | '/workspace/sermons/$sermonId'
    | '/workspace/sermons/choice'
    | '/workspace/sermons/new'
    | '/workspace/sermons/'
    | '/api/public/hooks/selah-weekly'
    | '/api/public/notifications/mark-read'
    | '/api/public/og/$handle'
    | '/hooks/calendar/$token/ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FinancesRoute: typeof FinancesRoute
  JourneyRoute: typeof JourneyRoute
  NotesRoute: typeof NotesRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReaderRoute: typeof ReaderRouteWithChildren
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TermsRoute: typeof TermsRoute
  VaultRoute: typeof VaultRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  _devBlueprintRoute: typeof _devBlueprintRoute
  _devIosSafeAreaRoute: typeof _devIosSafeAreaRoute
  _devReaderDiagnosticsRoute: typeof _devReaderDiagnosticsRoute
  _devSpinnersRoute: typeof _devSpinnersRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountBoardRoute: typeof AccountBoardRouteWithChildren
  ApiPublicGoogleTtsHealthRoute: typeof ApiPublicGoogleTtsHealthRoute
  ApiPublicReaderVoiceEngineRoute: typeof ApiPublicReaderVoiceEngineRoute
  ApiPublicSendPushRoute: typeof ApiPublicSendPushRoute
  ApiPublicHooksSelahWeeklyRoute: typeof ApiPublicHooksSelahWeeklyRoute
  ApiPublicNotificationsMarkReadRoute: typeof ApiPublicNotificationsMarkReadRoute
  ApiPublicOgHandleRoute: typeof ApiPublicOgHandleRoute
  HooksCalendarTokenIcsRoute: typeof HooksCalendarTokenIcsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/sermons': {
      id: '/workspace/sermons'
      path: '/sermons'
      fullPath: '/workspace/sermons'
      preLoaderRoute: typeof WorkspaceSermonsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/settings/service-mode': {
      id: '/settings/service-mode'
      path: '/service-mode'
      fullPath: '/settings/service-mode'
      preLoaderRoute: typeof SettingsServiceModeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/reading': {
      id: '/settings/reading'
      path: '/reading'
      fullPath: '/settings/reading'
      preLoaderRoute: typeof SettingsReadingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/intelligence': {
      id: '/settings/intelligence'
      path: '/intelligence'
      fullPath: '/settings/intelligence'
      preLoaderRoute: typeof SettingsIntelligenceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/calendar-sync': {
      id: '/settings/calendar-sync'
      path: '/calendar-sync'
      fullPath: '/settings/calendar-sync'
      preLoaderRoute: typeof SettingsCalendarSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reader/print': {
      id: '/reader/print'
      path: '/print'
      fullPath: '/reader/print'
      preLoaderRoute: typeof ReaderPrintRouteImport
      parentRoute: typeof ReaderRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account_/board': {
      id: '/account_/board'
      path: '/account/board'
      fullPath: '/account/board'
      preLoaderRoute: typeof AccountBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/billing': {
      id: '/account_/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dev/spinners': {
      id: '/__dev/spinners'
      path: '/spinners'
      fullPath: '/spinners'
      preLoaderRoute: typeof _devSpinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dev/reader-diagnostics': {
      id: '/__dev/reader-diagnostics'
      path: '/reader-diagnostics'
      fullPath: '/reader-diagnostics'
      preLoaderRoute: typeof _devReaderDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dev/ios-safe-area': {
      id: '/__dev/ios-safe-area'
      path: '/ios-safe-area'
      fullPath: '/ios-safe-area'
      preLoaderRoute: typeof _devIosSafeAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dev/blueprint': {
      id: '/__dev/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof _devBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/sermons/': {
      id: '/workspace/sermons/'
      path: '/'
      fullPath: '/workspace/sermons/'
      preLoaderRoute: typeof WorkspaceSermonsIndexRouteImport
      parentRoute: typeof WorkspaceSermonsRoute
    }
    '/workspace/sermons/new': {
      id: '/workspace/sermons/new'
      path: '/new'
      fullPath: '/workspace/sermons/new'
      preLoaderRoute: typeof WorkspaceSermonsNewRouteImport
      parentRoute: typeof WorkspaceSermonsRoute
    }
    '/workspace/sermons/choice': {
      id: '/workspace/sermons/choice'
      path: '/choice'
      fullPath: '/workspace/sermons/choice'
      preLoaderRoute: typeof WorkspaceSermonsChoiceRouteImport
      parentRoute: typeof WorkspaceSermonsRoute
    }
    '/workspace/sermons/$sermonId': {
      id: '/workspace/sermons/$sermonId'
      path: '/$sermonId'
      fullPath: '/workspace/sermons/$sermonId'
      preLoaderRoute: typeof WorkspaceSermonsSermonIdRouteImport
      parentRoute: typeof WorkspaceSermonsRoute
    }
    '/api/public/send-push': {
      id: '/api/public/send-push'
      path: '/api/public/send-push'
      fullPath: '/api/public/send-push'
      preLoaderRoute: typeof ApiPublicSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reader-voice-engine': {
      id: '/api/public/reader-voice-engine'
      path: '/api/public/reader-voice-engine'
      fullPath: '/api/public/reader-voice-engine'
      preLoaderRoute: typeof ApiPublicReaderVoiceEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-tts-health': {
      id: '/api/public/google-tts-health'
      path: '/api/public/google-tts-health'
      fullPath: '/api/public/google-tts-health'
      preLoaderRoute: typeof ApiPublicGoogleTtsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/board/share': {
      id: '/account_/board/share'
      path: '/share'
      fullPath: '/account/board/share'
      preLoaderRoute: typeof AccountBoardShareRouteImport
      parentRoute: typeof AccountBoardRoute
    }
    '/hooks/calendar/$token/ics': {
      id: '/hooks/calendar/$token/ics'
      path: '/hooks/calendar/$token/ics'
      fullPath: '/hooks/calendar/$token/ics'
      preLoaderRoute: typeof HooksCalendarTokenIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$handle': {
      id: '/api/public/og/$handle'
      path: '/api/public/og/$handle'
      fullPath: '/api/public/og/$handle'
      preLoaderRoute: typeof ApiPublicOgHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/mark-read': {
      id: '/api/public/notifications/mark-read'
      path: '/api/public/notifications/mark-read'
      fullPath: '/api/public/notifications/mark-read'
      preLoaderRoute: typeof ApiPublicNotificationsMarkReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/selah-weekly': {
      id: '/api/public/hooks/selah-weekly'
      path: '/api/public/hooks/selah-weekly'
      fullPath: '/api/public/hooks/selah-weekly'
      preLoaderRoute: typeof ApiPublicHooksSelahWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminWebhooksRoute: typeof AdminWebhooksRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminWebhooksRoute: AdminWebhooksRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ReaderRouteChildren {
  ReaderPrintRoute: typeof ReaderPrintRoute
}

const ReaderRouteChildren: ReaderRouteChildren = {
  ReaderPrintRoute: ReaderPrintRoute,
}

const ReaderRouteWithChildren =
  ReaderRoute._addFileChildren(ReaderRouteChildren)

interface SettingsRouteChildren {
  SettingsCalendarSyncRoute: typeof SettingsCalendarSyncRoute
  SettingsIntelligenceRoute: typeof SettingsIntelligenceRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsReadingRoute: typeof SettingsReadingRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsServiceModeRoute: typeof SettingsServiceModeRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCalendarSyncRoute: SettingsCalendarSyncRoute,
  SettingsIntelligenceRoute: SettingsIntelligenceRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsReadingRoute: SettingsReadingRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsServiceModeRoute: SettingsServiceModeRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkspaceSermonsRouteChildren {
  WorkspaceSermonsSermonIdRoute: typeof WorkspaceSermonsSermonIdRoute
  WorkspaceSermonsChoiceRoute: typeof WorkspaceSermonsChoiceRoute
  WorkspaceSermonsNewRoute: typeof WorkspaceSermonsNewRoute
  WorkspaceSermonsIndexRoute: typeof WorkspaceSermonsIndexRoute
}

const WorkspaceSermonsRouteChildren: WorkspaceSermonsRouteChildren = {
  WorkspaceSermonsSermonIdRoute: WorkspaceSermonsSermonIdRoute,
  WorkspaceSermonsChoiceRoute: WorkspaceSermonsChoiceRoute,
  WorkspaceSermonsNewRoute: WorkspaceSermonsNewRoute,
  WorkspaceSermonsIndexRoute: WorkspaceSermonsIndexRoute,
}

const WorkspaceSermonsRouteWithChildren =
  WorkspaceSermonsRoute._addFileChildren(WorkspaceSermonsRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceSermonsRoute: typeof WorkspaceSermonsRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSermonsRoute: WorkspaceSermonsRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface AccountBoardRouteChildren {
  AccountBoardShareRoute: typeof AccountBoardShareRoute
}

const AccountBoardRouteChildren: AccountBoardRouteChildren = {
  AccountBoardShareRoute: AccountBoardShareRoute,
}

const AccountBoardRouteWithChildren = AccountBoardRoute._addFileChildren(
  AccountBoardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FinancesRoute: FinancesRoute,
  JourneyRoute: JourneyRoute,
  NotesRoute: NotesRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReaderRoute: ReaderRouteWithChildren,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TermsRoute: TermsRoute,
  VaultRoute: VaultRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  _devBlueprintRoute: _devBlueprintRoute,
  _devIosSafeAreaRoute: _devIosSafeAreaRoute,
  _devReaderDiagnosticsRoute: _devReaderDiagnosticsRoute,
  _devSpinnersRoute: _devSpinnersRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountBoardRoute: AccountBoardRouteWithChildren,
  ApiPublicGoogleTtsHealthRoute: ApiPublicGoogleTtsHealthRoute,
  ApiPublicReaderVoiceEngineRoute: ApiPublicReaderVoiceEngineRoute,
  ApiPublicSendPushRoute: ApiPublicSendPushRoute,
  ApiPublicHooksSelahWeeklyRoute: ApiPublicHooksSelahWeeklyRoute,
  ApiPublicNotificationsMarkReadRoute: ApiPublicNotificationsMarkReadRoute,
  ApiPublicOgHandleRoute: ApiPublicOgHandleRoute,
  HooksCalendarTokenIcsRoute: HooksCalendarTokenIcsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
