/**
 * Pre-generated "Showroom" presets for the landing page Try It demo.
 *
 * These were batch-generated by MarQ (ai-anonymous-preview prompt, gemini-2.5-flash)
 * and frozen here so the landing-page demo costs $0 per visitor while preserving
 * MarQ's authentic Cinematic/Analytical voice.
 *
 * The 6 sectors form the "Power Lineup" — each chip shows the user their FUTURE
 * RESULT, not a generic category, to maximize click intent.
 *
 * To regenerate: run scripts/gen-try-it-presets (see /tmp/gen_presets.py in chat history).
 */

export interface TryItPreset {
  key: string;
  label: string;
  goal: string;
  /** Parsed MarQ output stages */
  stages: {
    audience: string;
    offer: string;
    hook: string;
    headline: string;
    subheadline: string;
    cta: string;
    lead_magnet: string;
  };
}

export const TRY_IT_PRESETS: TryItPreset[] = [
  {
    key: 'coaching',
    label: 'Scale a Premium Coaching Offer',
    goal: 'Scale a premium $5K coaching offer for ambitious experts ready to step into authority and command higher fees.',
    stages: {
      audience: 'Ambitious Experts: Struggling to scale their authority and command premium fees.',
      offer: 'Achieve $10K+ client acquisition through our Authority-to-Affluence Framework.',
      hook: 'Your expertise is undervalued. Stop competing. Start dominating.',
      headline: 'Authority. Amplified. Affluence. Assured.',
      subheadline:
        'Leverage proprietary frameworks to redefine your market value and secure elite client acquisition.',
      cta: 'Activate My Ascent',
      lead_magnet:
        'Authority Blueprint: The 7-Figure Expert Playbook. Full engine stages upon vaulting this strategic intelligence.',
    },
  },
  {
    key: 'saas',
    label: 'Build a SaaS Growth Engine',
    goal: 'Build a SaaS growth engine that converts free trial signups into paying teams through automated activation and habit loops.',
    stages: {
      audience: 'SaaS Founders: Struggling to convert trial users into sustained, paying team accounts.',
      offer:
        'Automated system deploying activation triggers and habit loops for trial-to-paid team conversion.',
      hook: 'Your best free trials are silently dying on the vine.',
      headline: 'Activate Free Trials. Monetize Teams.',
      subheadline:
        'Transform trial users into high-ARR organizational assets through intelligent, autonomous activation pathways.',
      cta: 'Deploy Activation Engine',
      lead_magnet:
        'The "Autonomous Activation Blueprint" for immediate trial-to-team insights. Full engine stages upon vaulting this strategic architecture.',
    },
  },
  {
    key: 'real_estate',
    label: 'Architect a Real Estate Authority',
    goal: 'Architect a real estate authority brand that captures qualified seller leads in luxury markets without paid ads.',
    stages: {
      audience: 'Luxury Homeowners: Frustrated by unfulfilled promises and opaque sales processes.',
      offer: 'Guaranteed 60-day accelerated sale of your luxury property for maximum market value.',
      hook: 'Your "exclusive" agent is costing you millions, not making them.',
      headline: "Unleash Your Property's True Market Power.",
      subheadline:
        'Access the proprietary methodology discerning luxury sellers use to command record-breaking offers, consistently.',
      cta: "Unlock Your Property's Valuation",
      lead_magnet:
        'Private White Paper: "The 1% Seller Stratagem." Secure this vault, and the full Revenue Engine stages.',
    },
  },
  {
    key: 'agency',
    label: 'Launch a Professional Agency',
    goal: 'Launch a professional boutique agency that signs $10K+ retainers from venture-backed founders needing brand and growth systems.',
    stages: {
      audience:
        'Venture-funded Founder: Scaling rapidly, requires structured brand voice and growth framework.',
      offer:
        'Deploy a proprietary Brand & Growth Engine, securing investor confidence and predictable market capture.',
      hook: 'Your VC funding is not a growth strategy. Your brand is.',
      headline: 'Engineer Your Market Dominance.',
      subheadline:
        'Translate investment capital into an unassailable brand architecture and an accelerating revenue trajectory.',
      cta: 'Activate Your Engine',
      lead_magnet:
        'A 3-Phase Strategic Blueprint: secure this initial intel, and the full Revenue Engine stages for your enterprise.',
    },
  },
  {
    key: 'expertise',
    label: 'Turn Expertise into Revenue',
    goal: 'Turn deep professional expertise into a productized revenue stream — books, micro-courses, and high-ticket strategy intensives.',
    stages: {
      audience: 'Expert Professionals: Stuck trading time for money, unable to scale their impact.',
      offer: 'Systemize expertise into productized revenue streams, unlocking scaled impact and wealth.',
      hook: 'Your "time for money" model is a revenue cap. Shatter it.',
      headline: 'Productized Expertise: Your Revenue Engine',
      subheadline:
        'Transform deep professional knowledge into scalable books, micro-courses, and high-ticket strategy intensives.',
      cta: 'Activate My Engine',
      lead_magnet:
        'The "Productized Expert Blueprint": Unlock the full engine — Lead Scoring, Sequences, and Performance Memory.',
    },
  },
  {
    key: 'course',
    label: 'Deploy a Digital Course System',
    goal: 'Deploy a digital course system that converts cold traffic into $297 enrollments through a 6-week transformation curriculum.',
    stages: {
      audience: 'Overwhelmed solopreneurs seeking a clear, repeatable system for consistent client acquisition.',
      offer:
        'Transform erratic lead flow into predictable client enrollment through a 6-week autonomous revenue engine deployment.',
      hook: 'Your "system" isn\'t selling. Mine deploys.',
      headline: 'Autonomous Revenue Engine: Deploy. Convert. Scale.',
      subheadline:
        'Stop chasing clients. Build the machine that attracts, qualifies, and converts your ideal customers on autopilot.',
      cta: 'Activate Your Engine',
      lead_magnet:
        'A 3-step Engine Blueprint. Secure this vault, and the full Lead Scoring, Sequences, and Performance Memory systems initiate.',
    },
  },
];
