// PDF Export utilities for Advanced Tools
import { format } from "date-fns";
import { escapeHtml as esc } from "./htmlEscape";

// Shared branding styles for all PDF exports
const brandStyles = `
  .brand-header {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 12px;
    margin-bottom: 12px;
  }
  .brand-logo {
    width: 48px;
    height: 48px;
    background: linear-gradient(135deg, #10b981 0%, #059669 100%);
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 24px;
  }
  .brand-name {
    font-size: 32px;
    font-weight: 700;
    color: #10b981;
  }
  .brand-tagline {
    color: #64748b;
    font-size: 14px;
    margin-bottom: 8px;
    text-align: center;
  }
  .footer-brand {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    margin-bottom: 8px;
  }
  .footer-logo {
    width: 20px;
    height: 20px;
    background: linear-gradient(135deg, #10b981 0%, #059669 100%);
    border-radius: 4px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 10px;
  }
  .footer-text {
    color: #10b981;
    font-weight: 600;
    font-size: 14px;
  }
  .footer-meta {
    color: #94a3b8;
    font-size: 12px;
    text-align: center;
  }
`;

const brandHeader = `
  <div class="brand-header">
    <div class="brand-logo">✨</div>
    <span class="brand-name">CoinsBloom</span>
  </div>
  <p class="brand-tagline">Smart Money Management for Everyone</p>
`;

const brandFooter = `
  <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center;">
    <div class="footer-brand">
      <div class="footer-logo">✨</div>
      <span class="footer-text">Generated by CoinsBloom</span>
    </div>
    <p class="footer-meta">${format(new Date(), "PPP 'at' p")} • coinsbloom.com</p>
  </div>
`;

export const exportBusinessExpensesPDF = (expenses: Array<{
  expense_date: string;
  description: string;
  category: string;
  amount: number;
  is_deductible: boolean;
}>) => {
  const totalAmount = expenses.reduce((sum, e) => sum + Number(e.amount), 0);
  const deductibleAmount = expenses.filter(e => e.is_deductible).reduce((sum, e) => sum + Number(e.amount), 0);

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Business Expenses Report | CoinsBloom</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px; 
          color: #1a1a1a;
          line-height: 1.6;
        }
        ${brandStyles}
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #16a34a;
        }
        h1 { 
          color: #1e293b; 
          font-size: 24px;
          margin-bottom: 4px;
          font-weight: 600;
        }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        th { background-color: #f0fdf4; color: #15803d; font-weight: 600; }
        .total { font-weight: bold; font-size: 1.1em; }
        .deductible { color: #16a34a; }
        .summary { margin-top: 30px; padding: 20px; background: #f0fdf4; border-radius: 12px; }
        .date { color: #64748b; font-size: 14px; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        ${brandHeader}
        <h1>Business Expenses Report</h1>
        <p class="date">Generated: ${format(new Date(), "PPP")}</p>
      </div>
      
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Category</th>
            <th style="text-align: right;">Amount</th>
            <th style="text-align: center;">Deductible</th>
          </tr>
        </thead>
        <tbody>
          ${expenses.map(e => `
            <tr>
              <td>${esc(e.expense_date)}</td>
              <td>${esc(e.description)}</td>
              <td style="text-transform: capitalize;">${esc(e.category.replace(/_/g, " "))}</td>
              <td style="text-align: right;">$${Number(e.amount).toLocaleString()}</td>
              <td style="text-align: center;">${e.is_deductible ? "✓" : "—"}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>

      <div class="summary">
        <p class="total">Total Expenses: $${totalAmount.toLocaleString()}</p>
        <p class="total deductible">Tax Deductible: $${deductibleAmount.toLocaleString()}</p>
      </div>
      
      ${brandFooter}
    </body>
    </html>
  `;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  }
};

export const exportDonationsPDF = (donations: Array<{
  donation_date: string;
  organization: string;
  donation_type: string;
  amount: number;
  is_tax_eligible: boolean;
}>) => {
  const totalAmount = donations.reduce((sum, d) => sum + Number(d.amount), 0);
  const taxEligibleAmount = donations.filter(d => d.is_tax_eligible).reduce((sum, d) => sum + Number(d.amount), 0);

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Charitable Donations Report | CoinsBloom</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px; 
          color: #1a1a1a;
          line-height: 1.6;
        }
        ${brandStyles}
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #db2777;
        }
        h1 { 
          color: #1e293b; 
          font-size: 24px;
          margin-bottom: 4px;
          font-weight: 600;
        }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        th { background-color: #fdf2f8; color: #be185d; font-weight: 600; }
        .total { font-weight: bold; font-size: 1.1em; }
        .eligible { color: #16a34a; }
        .summary { margin-top: 30px; padding: 20px; background: #fdf2f8; border-radius: 12px; }
        .date { color: #64748b; font-size: 14px; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        ${brandHeader}
        <h1>Charitable Donations Report</h1>
        <p class="date">Generated: ${format(new Date(), "PPP")}</p>
      </div>
      
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Organization</th>
            <th>Type</th>
            <th style="text-align: right;">Amount</th>
            <th style="text-align: center;">Tax Eligible</th>
          </tr>
        </thead>
        <tbody>
          ${donations.map(d => `
            <tr>
              <td>${esc(d.donation_date)}</td>
              <td>${esc(d.organization)}</td>
              <td style="text-transform: capitalize;">${esc(d.donation_type.replace(/_/g, " "))}</td>
              <td style="text-align: right;">$${Number(d.amount).toLocaleString()}</td>
              <td style="text-align: center;">${d.is_tax_eligible ? "✓" : "—"}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>

      <div class="summary">
        <p class="total">Total Donations: $${totalAmount.toLocaleString()}</p>
        <p class="total eligible">Tax Eligible: $${taxEligibleAmount.toLocaleString()}</p>
      </div>
      
      ${brandFooter}
    </body>
    </html>
  `;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  }
};

export const parseCSVImport = (csvText: string): Array<Record<string, string>> => {
  const lines = csvText.trim().split("\n");
  if (lines.length < 2) return [];
  
  const headers = lines[0].split(",").map(h => h.trim().toLowerCase().replace(/\s+/g, "_"));
  const records: Array<Record<string, string>> = [];
  
  for (let i = 1; i < lines.length; i++) {
    const values = lines[i].split(",").map(v => v.trim().replace(/^"|"$/g, ""));
    const record: Record<string, string> = {};
    headers.forEach((header, idx) => {
      record[header] = values[idx] || "";
    });
    records.push(record);
  }
  
  return records;
};
